export const USE_COMPUTER = 'USE_COMPUTER';
export const LEFT_COMPUTER = 'LEFT_COMPUTER';
// export const RETREIVE_COMPUTER_IS_AVAILABLE = 'RETREIVE_COMPUTER_IS_AVAILABLE';
// export const RETREIVE_COMPUTER_CURRENT_ADDRESS = 'RETREIVE_COMPUTER_CURRENT_ADDRESS';

// export const USE_COMPUTER_STARTED = 'USE_COMPUTER_STARTED';
// export const USE_COMPUTER_COMPLETED = 'USE_COMPUTER_COMPLETED';

// export const LEFT_COMPUTER_STARTED = 'LEFT_COMPUTER_STARTED';
// export const LEFT_COMPUTER_COMPLETED = 'LEFT_COMPUTER_COMPLETED';

export const RETREIVE_COMPUTER_IS_AVAILABLE_STARTED = 'RETREIVE_COMPUTER_IS_AVAILABLE_STARTED';
export const RETREIVE_COMPUTER_IS_AVAILABLE_COMPLETED = 'RETREIVE_COMPUTER_IS_AVAILABLE_COMPLETED';

export const RETREIVE_COMPUTER_CURRENT_ADDRESS_STARTED = 'RETREIVE_COMPUTER_CURRENT_ADDRESS_STARTED';
export const RETREIVE_COMPUTER_CURRENT_ADDRESS_COMPLETED = 'RETREIVE_COMPUTER_CURRENT_ADDRESS_COMPLETED';
